name: diffusers-ct
channels:
  - astra-toolbox
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - astra-toolbox=2.3.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - expat=2.6.4
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=14.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - ncurses=6.4
  - openssl=3.4.1
  - pip=25.0
  - pydicom=3.0.1
  - python=3.12.8
  - readline=8.2
  - scipy=1.15.1
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - antlr4-python3-runtime==4.9.3
      - charset-normalizer==3.4.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - diffusers==0.32.2
      - filelock==3.17.0
      - fonttools==4.55.7
      - fsspec==2024.12.0
      - huggingface-hub==0.28.0
      - hydra-core==1.3.2
      - idna==3.10
      - importlib-metadata==8.6.1
      - jinja2==3.1.5
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - packaging==24.2
      - pillow==11.1.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.2
      - scikit-image==0.25.2
      - six==1.17.0
      - sympy==1.13.1
      - tifffile==2025.2.18
      - tokenizers==0.21.0
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.48.3
      - triton==3.1.0
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - zipp==3.21.0
      - mlcroissant==1.0.17

